name = "sportmind-ai"
compatibility_date = "2025-06-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "sportmind-db"
database_id = "a3645370-9562-4c12-a757-c079776bb977"

[[kv_namespaces]]
binding = "CACHE"
id = "fe90662e06df4de88d03236ed68ddfc0"

[[queues.producers]]
binding = "SCORING_QUEUE"
queue = "scoring-queue"

[[queues.producers]]
binding = "AI_REPORT_QUEUE"
queue = "ai-report-queue"
